### ISSUE TITLE
Options to highlight concepts like scope, macro depth, and nesting

### ISSUE THREAD

**Issue by priyadarshan** [DalekBaldwin/highlight-backquotes-mode#1]
Hi, I am not sure if you followed a short thread about your very nice library over at Reddit, this comment in particular struck me as potentially quite useful in this context:

"For highlighting concepts like scope, macro depth, and nesting (rainbow parens), we need richer decorative conventions such as boxes, shading, and icons." [justinmk](https://www.reddit.com/r/emacs/comments/2ryc0q/visualize_the_quotation_depth_of_lisp_code_in)

I must say I am an absolute beginner in Lisp. Having used `highlight-backquotes-mode`, I wonder if it would be possible to add options to highlight those constructs (scope, macro depth, etc) with more than colors, like underline, arrows or boxes?

In any case, thank you so much for `highlight-backquotes-mode`.

**Comment by DalekBaldwin** [comment]
I don't see much value in highlighting parentheses, but you can pretty much do that already. If you turn on `rainbow-delimiters-mode` before `highlight-backquotes-mode`, it will override the colors on every paren.

Visualizing scope information would require much more semantic awareness, especially since one of the main uses of macros is to manipulate bindings. It _might_ be feasible it you restricted it to code that only used special forms and built-in macros. You could probably make it a little more complete and correct by hooking into a running Lisp process through SLIME, but you'd have to take a whole lot of late-bound information and send it really far upstream in the linguistic pipeline, so to speak.

**Comment by priyadarshan** [comment]
Thank you for the detailed answer, very instructive. And thank you again for  for `highlight-backquotes-mode`! (ps: Feel free to close this issue any time.)
